# Generated by Django 5.2.5 on 2025-08-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_japanese', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='manga')),
                ('status', models.CharField(choices=[('publishing', 'Publishing'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], max_length=20)),
            ],
        ),
    ]
